#!/bin/bash

echo "Content-Type: text/html"
echo ""

# load small-shell conf
. /var/www/descriptor/.small_shell_conf

# load remote addr
remote_addr=`echo $REMOTE_ADDR | $SED "s/:/-/g"`

IP_whitelisting=no

# IP restriction check
if [ "$IP_whitelisting" = "yes" ];then
  whitelist_chk=`${small_shell_path}/bin/meta get.IP | grep -v "NO IP RESTRICTION"`
  if [ "$whitelist_chk" ];then
    for IP in $whitelist_chk
    do
      IP=`echo $IP | $SED "s/*//g"`
      if [[ ${remote_addr} == ${IP}* ]];then
        IP_chk_flag=yes
        break
      fi
    done
   
    if [ ! "$IP_chk_flag" = "yes" ];then
      echo "error: your IP is not allowed to access"
      exit 1
    fi
  fi
fi

# auth for small-shell databox
authkey="Ym9va2luZ19yZXEuYXBwOmIzYmVjMmJlOTA5OWM4YzNhNzAzMDllZTc1YWUxNzM1MWYxMTU1NmYK"
auth_req=`${small_shell_path}/bin/extension_auth key_auth:${authkey} remote_addr:${remote_addr} app:booking_req user_agent:booking_req`
user_name=`echo $auth_req | $AWK -F "," '{print $1}' | $AWK -F ":" '{print $2}'`
session=`echo $auth_req | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}'`
pin=`echo $auth_req | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}'`


param=`date +%s`
param="$param:$RANDOM"
count=1

while [ -f /var/www/tmp/${param} ]
do
 sleep 0.01
 count=`expr $count + 1`
 if [ $count -eq 100 ];then
   echo "error: please contact to adimin"
   exit 1
 fi
done


# parse QUERY_STRING
echo $QUERY_STRING | $PHP -r "echo urldecode(file_get_contents('php://stdin'));" | tr -d \$ | tr -d \` | $SED "s/\&/\n/g" > /var/www/tmp/${param}
cat /var/www/tmp/${param} | $SED -e "s/=/=\"/1" | $SED "s/$/\"/g" | $SED "s/^\"//g" > /var/www/tmp/${param}.load
chmod 755 /var/www/tmp/${param}.load

# load query string
.  /var/www/tmp/${param}.load
rm  /var/www/tmp/${param}*

# dump POST data
if [ "`echo $REQUEST_METHOD | grep -i "POST"`" ];then

  if [ "`echo $CONTENT_TYPE | grep "application/json"`" ];then
    method=json
  elif [ "`echo $CONTENT_TYPE | grep "multipart/form-data"`" ];then
    method=multipart
  elif [ "`echo $CONTENT_TYPE | grep "application/octet-stream"`" ];then
    method=data-binary
  else
    method=urlenc
  fi

  mkdir /var/www/tmp/$session
  # dump posted data
  dd bs=${CONTENT_LENGTH} of=/var/www/tmp/$session/input 2>/dev/null
  /var/www/bin/parse.sh $session $method

fi

#----------------------------
# routing to action scripts
#----------------------------

if [ ! "$req" ];then
  req=get
fi

case "$req" in

  "get")
    # comment out original line
    #/var/www/bin/booking_req_get.sh session:$session pin:$pin id:$id remote_addr:${remote_addr};;
    # insert new line
    /var/www/bin/booking_req_get.sh session:$session pin:$pin id:$id remote_addr:${remote_addr} book_name:${book_name} ;;

  "set")
    /var/www/bin/booking_req_set.sh session:$session pin:$pin id:$id remote_addr:${remote_addr};;

  *)
    echo "error: wrong request";;

esac

exit 0
